apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a5me6ef5y-python
  janus-idp.io/tekton: a5me6ef5y-python
  backstage.io/kubernetes-id: a5me6ef5y-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a5me6ef5y-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
