apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: a5me6ef5y-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a5me6ef5y-python 
  name: a5me6ef5y-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: a5me6ef5y-python 
